version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${POSTGRES_URI}
    networks:
      - task


  db:
    image: postgres:13-alpine
    ports:
      - "8866:5432"
    restart: always
    command: "postgres -c max_connections=150
                 -c shared_buffers=512MB -c effective_cache_size=1536MB
                 -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB
                 -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200
                 -c work_mem=3495kB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=2
                 -c max_parallel_workers_per_gather=1 -c max_parallel_workers=2 -c max_parallel_maintenance_workers=1"
    environment:
      POSTGRES_DB: async_task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

    env_file:
      - '.env'
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task

networks:
  task:
    driver: bridge


volumes:
  postgres_data: { }
